# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  paddidemousagesapidemo:
    image: paddidemousagesapidemo
    build:
      context: .
      dockerfile: src/services/Paddi.DemoUsages.ApiDemo/Dockerfile
    ports:
      - 5123:5123
  
  redis:
    image: redis
    ports:
      - "6379"
  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12349876"
      MYSQL_DATABASE: "paddi_demo"
    ports:
      - "3306"

